COMPONENT=MultihopOscilloscopeAppC
BOOTLOADER=tosboot
#CFLAGS+=-DDELUGE_LIGHT_BASESTATION
CFLAGS += -I$(TOSDIR)/lib/net/ -I$(TOSDIR)/lib/net/ctp  -I$(TOSDIR)/lib/net/4bitle 


# Set channel for communication in iris and micaz in range 11- 26
#PFLAGS+=-DCC2420_DEF_CHANNEL=26
#PFLAGS+=-DRF230_DEF_CHANNEL=26

include $(MAKERULES)
